### ISSUE TITLE
Feature knowledge

### ISSUE THREAD

**Issue by ddarji1409** [yjg30737/pyqt-openai#172]
I am still trying to understand the concrete use case of this module.

The SW doesn't know anything going on my PC yet.

What is the point of integrating this QT gui with my PC?

**Comment by yjg30737** [comment]
Python QT gui is one of the things i'm very good at. So i chose that one.
Also it can be used broadly in Windows, MacOS, Linux, and embedded device such as Raspberry Pi.
One of the ultimate goal of this is adapting this into embedded device.
