### ISSUE TITLE
sqlite3.OperationalError: duplicate column name: engine

### ISSUE THREAD

**Issue by petervflocke** [yjg30737/pyqt-openai#19]
Hi Gyu Yoon,

Nice job, thank you for sharing!

I like your idea of replicating the playground and extending this with some additional features.
A few observation from my side:
Not installing your application and simply calling python3 main.py I'm getting following problem:
`peter@alfa:~/Development/AI-and-chatGPT/pyqt-openai/pyqt_openai$ python3 main.py 
Traceback (most recent call last):
  File "/home/peter/Development/AI-and-chatGPT/pyqt-openai/pyqt_openai/main.py", line 16, in <module>
    from pyqt_openai.apiData import getModelEndpoint
` 
Solution: move main.py one folder higher to the root of the repo.
and modify line 6 and 7:

```
from pyqt_openai.chatWidget import Prompt, ChatBrowser

from pyqt_openai.notifier import NotifierWidget
```

When I start the main.py module for the very first time I'm getting following error:

`sqlite3.OperationalError: duplicate column name: engine`

You have a typo in the file pyqt_openai/sqlite.py

`
engine TEXT DEFAULT '{self.__chat_default_value['system']}',
`

It should be:

`
system TEXT DEFAULT '{self.__chat_default_value['system']}',
`

The code does not work with GPT-4.
in the main.py line 433:
`
if info_dict['engine'] in ['gpt-3.5-turbo', 'gpt-3.5-turbo-0301']:
`
gpt-4 engine version is missing. quick fix:
`
if info_dict['engine'] in ['gpt-3.5-turbo', 'gpt-3.5-turbo-0301', 'gpt-4']:
`

As I'm going to change few additional things, do you mind if I fork your code? I will keep your name and licence model.

Sorry I did not prepare PR, just wanted to inform you :)

Regards
Peter

**Comment by yjg30737** [comment]
Hello, Peter.

Thanks to point that out. i should've tested it out some more rather than using my previous db. 😥

You can fork whenever you want since this is open-source :)

**Comment by petervflocke** [comment]
> You can fork whenever you want since this is open-source :)

Great thanks let's stay in contact.
