### ISSUE TITLE
ModuleNotFoundError: No module named 'pyqt_openai'

### ISSUE THREAD

**Issue by petervflocke** [yjg30737/pyqt-openai#33]
Hi Gyu Yoon,

hope you are doing well!

I'd like to draw you attention to still open an old issue. 
You cannot run your code without going through setup process, just as mentioned [here](https://github.com/yjg30737/pyqt-openai#how-to-install).

I believe you went through setup process (`python setup.py install`) at least once and the modules are on the path. If you try to follow the steps from above link  in a fresh environment you will get this:

```bash
peter@alfa:~/Development/AI-and-chatGPT/pyqt-openai$ ll
total 44
drwxrwxr-x  5 peter peter 4096 Mai 28 19:24 ./
drwxrwxr-x 15 peter peter 4096 Mai 28 19:24 ../
drwxrwxr-x  8 peter peter 4096 Mai 28 19:24 .git/
-rw-rw-r--  1 peter peter 1860 Mai 28 19:24 .gitignore
drwxrwxr-x  3 peter peter 4096 Mai 28 19:24 .idea/
-rw-rw-r--  1 peter peter 1070 Mai 28 19:24 LICENSE
drwxrwxr-x  8 peter peter 4096 Mai 28 19:24 pyqt_openai/
-rw-rw-r--  1 peter peter 5946 Mai 28 19:24 README.md
-rw-rw-r--  1 peter peter   66 Mai 28 19:24 requirements.txt
-rw-rw-r--  1 peter peter 1165 Mai 28 19:24 setup.py
peter@alfa:~/Development/AI-and-chatGPT/pyqt-openai$ cd pyqt_openai/
peter@alfa:~/Development/AI-and-chatGPT/pyqt-openai/pyqt_openai$ python3 main.py 
Traceback (most recent call last):
  File "/home/peter/Development/AI-and-chatGPT/pyqt-openai/pyqt_openai/main.py", line 10, in <module>
    from pyqt_openai.aboutDialog import AboutDialog
ModuleNotFoundError: No module named 'pyqt_openai'
peter@alfa:~/Development/AI-and-chatGPT/pyqt-openai/pyqt_openai$ 
```

**Comment by yjg30737** [comment]
I have to admit that i'm not familiar with Linux so i've installed the Ubuntu in VirtualBox to use pyqt-openai

I didn't go through `python setup.py install` because in Windows 11 it works even if i don't do it. Python in Windows adds current path to env path to make it work, unlike Linux.

So i had to consider Linux user.. 😥 very sorry. Thanks for bringing up this

After run `python setup.py install`, it works and i've just added it in README

**Comment by petervflocke** [comment]
> After run `python setup.py install`, it works and i've just added it in README
Hi thanks for the efforts in checking this in details! I looked into the details as well. If someone does not want to install it and still test it in a local folder, it is enough to add to the PYTHONPATH variable path to the "pyqt-openai" folder.

So a quick workaround is to run the command from the folder where you clone the repo
`peter@alfa:~/Development/AI-and-chatGPT/pyqt-openai$ export PYTHONPATH=$(pwd):$PYTHONPATH`

or add to your .profile or .bashrc file a fixed path:
`export PYTHONPATH=~/Development/AI-and-chatGPT/pyqt-openai:$PYTHONPATH`

This helps python to find embedded modules in the pyqt-openai folder.
