### ISSUE TITLE
No module named 'llama_index.response'

### ISSUE THREAD

**Issue by laurenceanthony** [yjg30737/pyqt-openai#99]
After installing everything from the requirements.txt file, I'm running into the following problem:
No module named 'llama_index.response'

Is the code set up for an old version of llama_index?

**Comment by yjg30737** [comment]
As a temporary measure, I've just removed llama-index package in pyqt-openai which causes error, since usage of llama-index is significantly changed.  

I will create tag to figure out how to implement "new" llama-index in this package.

**Comment by laurenceanthony** [comment]
Sounds good. Once I get a working version here, I'll see if I can contribute to it.

**Comment by yjg30737** [comment]
It is bit too late (which is an understatement) but i applied new llamaindex codes into feature/llamaindex branch just a couple of days ago. If there are no issues, I will merge it this weekend.
